### ISSUE TITLE
Device Management will need some love

### ISSUE THREAD

**Issue by grintor** [tier2tickets/Feedback#1]
Device Management will need some love, going to be a beast to deal with if we’ve got +1k agents in there. Need to be able to at least easily search/filter through the list. That said this is a pain point with our current solution as well, they don’t do automatic cleanup. It’d be awesome to see agents automatically deactivate after a certain period of time/help us keep the list accurate. I’m fine with making our technicians check there to remove agents as a v1 but it would be tough in its current format.

**Comment by pmfjoe** [comment]
I would say have the option to automatically remove devices that haven't been "seen" in 60-90 days, also be able to sort by the column headers so we could manually remove old agents.

I assume if a PC is re-imaged then the old agent would automatically be replaced or removed when the new one is added since the mac address would be the same?

**Comment by xetnez** [comment]
I would like to add that this page really needs "containers" or "folders". Some way to group devices by clients. As an MSP this sort of grouping is detrimental in finding devices.

**Comment by grintor** [comment]
@xetnez we now have the sorting and grouping ability on that page, so I am going to close this now. Let us know if you think of anything else. Thank you for your feedback
