### ISSUE TITLE
Website "Backend Information" Update

### ISSUE THREAD

**Issue by MSPNinjas** [tier2tickets/Feedback#18]
When changing the settings on the "Backend Information" section you are required to enter the input password and repeat password fields, almost as if you would do a password reset. Is this by design to verify you want to make the change? Maybe just a prompt to enter the password a single time when you want to save a setting on that page if that was the intent.

Also, the "Business Name" field keeps resetting to use my email address instead of the Business Name. 

I am using Chrome Version 75.0.3770.142 (Official Build) (64-bit)

**Comment by elcopeland** [comment]
Hello! this behavior sounds like something we definitely don't want happening. Will you give us a little more info at [support@tier2tickets.com](mailto:support@tier2tickets.com)?

**Comment by grintor** [comment]
I have seen this happen in the wild. It's not on our end. Some people have password manager plugins that are aggressively autofilling the page. It's autofilling the password field which is causing it to not match the confirm password field because it has dummy text in it. I'm not sure which password manager is doing this. @MSPNinjas can you tell us which password manager you are using so we can test how to prevent this?

**Comment by MSPNinjas** [comment]
I use a mix of LastPass and Passportal in Chrome

**Comment by grintor** [comment]
@MSPNinjas I added the autocomplete="new-password" attribute to the input field. Can you see if that fixed the issue for you?

**Comment by xetnez** [comment]
I use lastpass/chrome and it still auto-pops the passwd boxes. I remove the passwd and click update and I still get "password is not valid" even though I cleared that field. It acts like it requires the passwd to change any info on that screeen

**Comment by grintor** [comment]
Ok, I have made it so that you can leave the password field blank and it will ignore it on that page now.
