### ISSUE TITLE
Integration issue causes ticket to not submit

### ISSUE THREAD

**Issue by Tedward747** [tier2tickets/Feedback#45]
If you have issues with your integration (i.e. I did not set up the 'unregistered' user on my end) that causes a ticket to fail to be created, the user who pressed the button gets the error making it look like their internet is down and no information is sent.

Is it possible to have it fall back to email if there is an issue creating a ticket?

**Comment by grintor** [comment]
It's not possible at this time, but that's not a bad idea. I am worried that the email might not be monitored as closely as the ticket system sometimes and that tickets will get lost though. We are working on getting a test button added to the settings page for the integration. I think just having a comprehensive test in place so that there are none of these types of failures would be the best solution here. What do you think?

**Comment by Tedward747** [comment]
That would indeed solve the issue of people like me who don't always bother reading all the steps (users, eh?), but still leaves a potential gap if there's some form of service outage between tier2 and the PSA.  I'd bet almost every MSP out there has a support@ email that forwards to their ticketing system anyhow, so if it was possible to have the email integration configured as a backup it would let me sleep a little easier.

Slightly expanded idea would be to accept the ticket into tier2 and keep it queued, retry every few minutes, and if after say 15 minutes it hasn't been able to send it through fall back to email at that point?

Keep in mind from the users perspective, if they're already having problems to the point of opening a ticket, they fill out all the info, hit submit, then get told the ticketing system isn't working either..

**Comment by grintor** [comment]
We have had another feature request for what I think will be an simple to implement feature that fills the gap here. The feature request is for an additional optional CC: field on the settings page where you can put an email address to CC: every ticket on. It's kind of a way to have both a ticket system integration and email connector both running at the same time. I am imagining the email still coming through despite the PSA being down would accomplish this need. What do you think?

**Comment by Tedward747** [comment]
For this issue I feel like that would just turn into noise.  It wouldn't make sense to have a CC go to our support address because that would cause a second ticket every time, so it would need to go to a separate email, and unless it was an extended downtime it wouldn't be obvious if a single ticket failed to show up in our PSA but is sitting in an unlinked inbox.  (Sorry if I'm coming across as difficult here, I don't foresee integrations failing often, but it definitely can happen and I'm just not too warm and fuzzy on the current "looks like your internet is down even though it isn't, sorry you just wasted time filling out the form just to have to call us after all" setup).

I do like the CC idea in general, but I feel like it's more as a backup in case our entire PSA goes down for a while so we can still limp along on tickets, and/or for MM type owners/account managers who want to keep tabs on incoming tickets without needing to pop open the PSA.

**Comment by grintor** [comment]
@Tedward747,

We have since worked hard on making sure that the ticket goes in if there is a problem. In the API we now keep dropping off any configuration options that are hanging it up and just put it in with default settings, but we actually even took it to the extreme and allow the user to put in the ticket even if their computer doesn't have internet by showing them a QR code which if scanned will take the ticket the rest of the way using their phone. And we fall back to email if all that fails. So I think we have checked all the boxes here and I'm going to close this issue, but if you have any other good ideas please feel free to reopen it. Thank you again for your feedback, it really helps

Chris
