### ISSUE TITLE
Fatal error detected - Failed to execute script pyi_rth_pkgres upon launch in Windows 8.1

### ISSUE THREAD

**Issue by justinswall** [tier2tickets/Feedback#53]
Upon logon into a workstation running Windows 8.1 with the latest updates (as of January 17, 2020) the following error dialogue box appears:

Title:  Fatal error detected
Body:  Failed to execute script pyi_rth_pkgres

I used process explorer to verify that this dialogue box was being generated by buttonHelper.exe

**Comment by grintor** [comment]
Thanks for letting us know. This sounds like an error caused by missing
files installed in the program folder. We have seen this happen in cases
where the antivirus deleted some of the *.pyd files. Could you try
reinstalling the latest build with the program install folder whitelisted
in the antivirus and see if the problem persists? Could you check the
antivirus logs and see if anything was removed? In the next version, we
plan to throw more informative errors in this case.

Chris

**Comment by grintor** [comment]
If you are able to reproduce this please let me know. We have been working with AV vendors to prevent this from happening and I think it should be resolved now. Thank you for reporting it to us.

Chris
