### ISSUE TITLE
Cannot install software during custom script execution step of the button install

### ISSUE THREAD

**Issue by litigationjackson** [tier2tickets/Feedback#54]
Hey, when I try to install anything with the install.ps1 custom script included in my payload.zip, it isn't able to install since it's being blocked by the button installer. So I can't load Ninja or Screenconnect through the button install. Apologies if I'm missing something obvious.

**Comment by grintor** [comment]
Can you provide more details? What's the contents of your install.ps1?

**Comment by litigationjackson** [comment]
I've included an MSI installer in payload.zip, and currently install.ps1 just executes it. 
![image](https://user-images.githubusercontent.com/6867218/75055703-62eada80-548a-11ea-8fca-3af89a2e5282.png)
I've tried a few things to get around this, but figured I should bring this up in case it's something you'd like to know.

**Comment by grintor** [comment]
Ah, yes. This is because the Microsoft Installer Service cannot handle
installing more than one MSI package at a time. Since the helpdeskbuttons
software is still in the process of installation, you cannot start the
install of another MSI. The trick here is to install using an exe installer
rather than an MSI installer. Typically you can find an exe version of an
installer either from the software distributor or by extracting the MSI
Package. If you would like help extracting the MSI, we would be glad to
take a look at it. Just email the installer to support@helpdeskbuttons.com

Chris

**Comment by litigationjackson** [comment]
Odd, I tried the exe installer first and had the same problem. I'll look into it and get back to you.

**Comment by litigationjackson** [comment]
Yep looks like its just a problem with the specific program I'm trying to install. Sorry to bother.
