### ISSUE TITLE
One device shows up twice - one for each nic

### ISSUE THREAD

**Issue by chavousc** [tier2tickets/Feedback#55]
Single device gets counted as two when it switches from wired to wifi, (seemingly?) because macs are different between the two interfaces.  This should be counted as one device.  

![image](https://user-images.githubusercontent.com/35151752/75305314-c3c03d00-5813-11ea-90a5-c7dacb50e713.png)

**Comment by grintor** [comment]
Thanks @chavousc,

This is an issue that we think we have resolved in the newest version of the software. We now report the first mac address that is used to talk to the API as the official mac and save it in a config file so that it won't change if there are multiple mac addresses. If you use version 0.6.x.2 and above, you shouldn't see this issue again. But thank you again for taking the time to report this, your feedback is really important to us.

Chris
