### ISSUE TITLE
Program doesn't open on run

### ISSUE THREAD

**Issue by JoelPeeples** [tier2tickets/Feedback#64]
Sometimes the program will not open.  If I end the helpdesk system processes then it will open.  Right now, the program is not opening and the two tasks below are showing as running in task manager.  

I've attached the log files I found in the tier2tickets folder.

![image](https://user-images.githubusercontent.com/83021195/115734515-60fefe80-a34f-11eb-8955-0f47c079d33e.png)
[t2tservice.log](https://github.com/tier2tickets/Feedback/files/6359185/t2tservice.log)
[button.log](https://github.com/tier2tickets/Feedback/files/6359186/button.log)
[button_gui.log](https://github.com/tier2tickets/Feedback/files/6359187/button_gui.log)
[buttonHelper.log](https://github.com/tier2tickets/Feedback/files/6359188/buttonHelper.log)
[splash.log](https://github.com/tier2tickets/Feedback/files/6359190/splash.log)

**Comment by elcopeland** [comment]
Thanks for reporting this, @JoelPeeples, we'll take a look and track down what's causing this!

**Comment by JoelPeeples** [comment]
I'm still having this issue.  We're going to pause deployment until resolved.

**Comment by elcopeland** [comment]
The issue is related to profiles. If the user pairs the two, windows uses an existing profile's folder to store both an Azure AD and personal account login info. This may cause the owner of the folder to swap causing authentication issues when trying to read/write/execute things in that profile folder since the original owner may not have access to those files anymore.

**Comment by elcopeland** [comment]
Modified the custom identity provider in 1.1.x.18

**Comment by JoelPeeples** [comment]
Thank you, Elizabeth and Tier2Tickets teams!!
