### ISSUE TITLE
Duplicate connectwise tickets being logged

### ISSUE THREAD

**Issue by Xerihet** [tier2tickets/Feedback#66]
For a while now whenever our users press their button, we are seeing dual tickets logged - they have the same summary line, notes etc, and the Helpdesk button portal is only showing the first of these tickets as existing.

**Comment by elcopeland** [comment]
Thank you for the report @Xerihet, we’ll take a look ASAP.

**Comment by elcopeland** [comment]
Hey @Xerihet will you please email us at support@tier2.tech? We think we may know the source of this based on previous issues we've seen with ConnectWise but we need to know your account and what build you're on before we speculate further.

**Comment by TheGreatTSBob** [comment]
Our software is pretty aggressive about making sure the ticket gets into the ticket system. As a result we error on the side of duplicates instead of having a ticket simply fail to go in. Normally this is fine, since the request to create a ticket normally takes a second or two, The timeout on this request is now up to multiple minutes (upwards of 5) waiting for a success or failure message before trying to submit the ticket again.
