### ISSUE TITLE
guiTrigger.exe in different locations

### ISSUE THREAD

**Issue by ncrollo** [tier2tickets/Feedback#68]
I've been using HelpdeskButtons/Tier2Tickets since 9/13/2020 (I have several old installs). My current PSA/RMM is Syncro and I've followed all of the documentation to get the install script into my PSA as well as the procedure to Add Helpdesk Buttons to your Syncro System Tray Icon (https://docs.tier2tickets.com/content/deployment/syncro/#add-helpdesk-buttons-to-your-syncro-system-tray-icon)

It seems that some of my endpoints have the guiTrigger.exe still located in C:\Program Files (x86)\Helpdesk Button\. The install script runs daily but only checks that the t2tservice is running and does not validate that the correct file exists in the target path of "C:\Program Files (x86)\Tier2Tickets\guiTrigger.exe"

**Comment by cinakur** [comment]
Thanks for the heads' up, Nick. Our support team will be reaching out to help you with clean up and documentation.

**Comment by TheGreatTSBob** [comment]
@ncrollo 
This is a known issue related to changing the product name around 1.1.10. The most feasible way to fix this is to uninstall and reinstall so the installer puts the software in the Tier2Tickets folder instead of simply upgrading the install in the Helpdesk Button folder. 

While this does fix the issue, it will also cause the machines to not check-in as the endpoint it was tied to before. This will break the associations the between old reports and the endpoint and it will cause the endpoint to duplicate itself in the device management list. These duplicates will count toward your total endpoint count so you will want to either clean them up manually or wait for them to fall off automatically (assuming you have enabled this feature). You can read more about it in the docs here: https://docs.tier2tickets.com/content/deployment/uninstall/#managing-duplicate-endpoints

This can be accomplished at scale by adding something like this to the top of the update script. 

```powershell
if (Test-Path -Path 'C:\Program Files (x86)\Helpdesk Button\button.exe'){
     wmic product where (name="Helpdesk Button") call uninstall /nointeractive
}
```
